-- liquibase formatted sql

-- changeset it:1767375527109-67
ALTER TABLE designer_profiles DROP CONSTRAINT designer_profiles_user_id_ptr_fkey;

-- changeset it:1767375527109-57
ALTER TABLE designer_profiles
    ADD id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE designer_profiles
    ADD user_id INTEGER;

-- changeset it:1767375527109-59
ALTER TABLE designer_profiles
    ALTER COLUMN user_id SET NOT NULL;

-- changeset it:1767375527109-60
ALTER TABLE designer_profiles
    ADD CONSTRAINT uc_designer_profiles_user UNIQUE (user_id);

-- changeset it:1767375527109-65
ALTER TABLE designer_profiles
    ADD CONSTRAINT FK_DESIGNER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset it:1767375527109-79
ALTER TABLE designer_profiles DROP COLUMN user_id_ptr;

-- changeset it:1767375527109-52
ALTER TABLE designer_profiles
    ADD CONSTRAINT pk_designer_profiles PRIMARY KEY (id);

